### ISSUE TITLE
DoveTailJointCounterPart in CompoundEdge

### ISSUE THREAD

**Issue by MAKOMO** [florianfesti/boxes#3]
```
        self.open(50, 50)
        x = y = 10
        r = 0
        h = 46
        sep = 20 # 12
        self.surroundingWall(x,y,r,h,
            left=edges.CompoundEdge(self,["D","e"], [h-sep,sep]),
            right=edges.CompoundEdge(self,["e","d"], [sep,h-sep]))
        self.close()
```

renders

<img width="334" alt="screen shot 2016-04-22 at 17 11 07" src="https://cloud.githubusercontent.com/assets/13909011/14745811/44c57d94-08ad-11e6-964a-6870eca45ee8.png">

The left edge is not what I expected. The right edge looks fine.

**Comment by MAKOMO** [comment]
Oh, and if I add `bottom='F'`I expected the total hight to increase by `thickness`. Isn't the height argument interpreted as the inner height? At least I was under the impression that some commits before that was the case. I might be wrong.

**Comment by ffesti** [comment]
Well, the surroundingWall was not really ready to have fully parametrized edges. Also nice catch on the "F" width mess up. Both should be fixed now.

**Comment by MAKOMO** [comment]
I confirm that the "F" width is back to normal with our latest commit. The compound left edge improved somewhat, but does still not render as I would expect it.

<img width="448" alt="screen shot 2016-04-26 at 21 14 04" src="https://cloud.githubusercontent.com/assets/13909011/14831040/2caf1e6e-0bf4-11e6-8c41-6426ae5e1534.png">

Why is there this 90 degree turn to the inside after the "D" edge? I would have expected just a straight line as on the right side.

**Comment by MAKOMO** [comment]
Ah, now I found where that 90 degree turn to the inside happens. It is in CompoundEdge/__call__ in the elif part. However, I get what I expect if I comment the "def startwidth" in DoveTailJointCounterPart.

**Comment by florianfesti** [comment]
Yup, the DoveTailJointCounterPart should be width zero so that the DoveTailJoint doesn't need any length of the surrounding wall. Fixed now.

**Comment by MAKOMO** [comment]
Yes, I think this issue is now closed, however, I now have another "CompoundEdge issue" in another place. I will investigate and potential have to open another issue...
